server:
  port: 80

spring:
  application:
    name: cloud-cosunmer-hystrix-order


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: hystrixOrder80
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2

  #设置feign客户端超时时间(OpenFeign默认支持ribbon)
#  ribbon:
#    #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#    ReadTimeout: 5000
#    #指的是建立连接后从服务器读取到可用资源所用的时间
#    ConnectTimeout: 5000

  #这个配置配合feigh找不到提供方是默认处理方法使用，
  # @FeignClient(value = "CLOUD-PROVIDER-HYSTRIX-PAYMENT", fallback = PaymentFallbackService.class)
  # 但是会导致rebbon超时时间失效，有冲突
feign:
  hystrix:
    enabled: true